### ISSUE TITLE
Nerd font would be appreciated

### ISSUE THREAD

**Issue by thunfischbrot** [shytikov/pragmasevka#1]
Hi Oleksii,

thank you for this effort! I would like to continue using the nerd font, it is a very nice addition.

**Comment by thinko** [comment]
I agree, +1 to Nerd Font glyphs.

**Comment by poetaman** [comment]
Here's the build patched with nerd font glyphs: [PragmasevkaNerdFontV1p2.zip](https://github.com/shytikov/pragmasevka/files/10101329/PragmasevkaNerdFontV1p2.zip)

**Comment by shytikov** [comment]
Hej @thunfischbrot, @thinko @poetaman I have reverted back `Nerd Fonts` patching, and also have tried to guess `xHeight`. Updated to very fresh `Iosevka` too. Please check the [new release](https://github.com/shytikov/pragmasevka/releases/tag/v1.3.0).

**Comment by thunfischbrot** [comment]
Pefect, thank you so much!
