### ISSUE TITLE
Increment line-height

### ISSUE THREAD

**Issue by MrJmpl3** [shytikov/pragmasevka#4]
Hi! This project is awesome, but I have a little question, How increase the line-height of the font?

**Comment by shytikov** [comment]
Hej!

Thank you for your interest! Sorry for such a long time needed to get back to you! 

I have adjusted line height to match PragmataPro, but if you want to change it, set greater value [here](https://github.com/shytikov/pragmasevka/blob/main/private-build-plans.toml#L16).

If you remove that line, it will use default value from Iosevka, which is far less cramped.

**Comment by shytikov** [comment]
I hope that answered the question! Please feel free to open the conversation again, if not!
